spring:
  application:
    name: cart-service

server:
  port: 6060

info:
  Service: Cart Service
  Version: 1.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
