spring:
  application:
    name: country-service

server:
  port: 7070


info:
  Service: Country Service
  Version: 1.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
