spring:
  application:
    name: volatility-index-service

server:
  port: 9090

info:
  Service: Volatility Index Service
  Version: 1.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
